### PR TITLE
feat: :sparkles: add autosize sidesheet width and remove margin-bottom: -15px from styledswitchboardwrapper

### PR DESCRIPTION
**Pull request by MagnusGjosund**
How to test: Open different sidesheets (circuit diagrams) in Electrical Consumers and check the sidesheet behavior. Expected behavior will be autosizing of the sidesheet witdh based on the citcuit diagram width, but minimum width will be the normal width of every sidesheet

### CODE REVIEW

**Comment by MagnusGjosund** [comment]
deploy test

**Comment by MagnusGjosund** [comment]
deploy test

**Comment by MagnusGjosund** [comment]
@AreWiv can you test the sidesheets in Electrical Consumers?

**Comment by AreWiv** [comment]
@MagnusGjosund Any tag nos that provide relevant testing?

**Comment by MagnusGjosund** [comment]
Not sure i understand the question. You can test any tags, and you should find tags with different size of the circuit diagram in the sidesheet

**Comment by AreWiv** [comment]
Tested and verified.

**Pull request merged**
