### PR TITLE
Link workspace locally

### PR DESCRIPTION
**Pull request by Gustav-Eikaas**
Added a script to link Workspace package locally. This has been done manually for some time now. 
Not sure how much effort we should put into this convenience. Like e.x should it tell you if workspace is behind main by x commits?

**Note:** Encountered a weird bug where if I build workspace from root it behaves differently from when building a specific package. Unrelated to this pull request there might be some sort of bug with turbo caching or possibly tsup

### CODE REVIEW

**Comment by kjellhaaland** [comment]
@Gustav-Eikaas This should be mentioned in the README somewhere.

**Comment by Gustav-Eikaas** [comment]
Yes you are right! Added it now

**Review by kjellhaaland — COMMENTED** [review]
Tested this locally and it worked great!

Good job Gustav! :fire:

**Review by kjellhaaland — APPROVED** [review]
Approved :tada:

**Pull request merged**
