### PR TITLE
🔖Bump workspace-fusion@6.0.10

### PR DESCRIPTION
**Pull request by Gustav-Eikaas**
Fixes:
- [x] equinor/fusion-workspace#523
- [x] equinor/fusion-workspace#515  equinor/fusion-workspace#512  equinor/fusion-workspace#504
- [x]  equinor/fusion-workspace#526
- [x]  equinor/fusion-workspace#505
- [x] equinor/fusion-workspace#533
- [x] equinor/lighthouse-client#1476
- [x] equinor/lighthouse-client#1477

### CODE REVIEW

**Comment by Gustav-Eikaas** [comment]
deploy test

**Comment by Gustav-Eikaas** [comment]
deploy test

**Comment by Gustav-Eikaas** [comment]
deploy test

**Comment by Gustav-Eikaas** [comment]
6.0.3 had a crashing issue on powerbi persistence

**Comment by Gustav-Eikaas** [comment]
deploy test

**Review by espenkalle — APPROVED** [review]

**Comment by Gustav-Eikaas** [comment]
deploy test

**Comment by Gustav-Eikaas** [comment]
deploy test

**Comment by Gustav-Eikaas** [comment]
deploy test

**Pull request merged**
