### PR TITLE
fix(workspace): garden popover not closing on outside click

### PR DESCRIPTION
**Pull request by Gustav-Eikaas**
Fixed a bug where outside click does not close the garden popover.

### CODE REVIEW

**Comment by Gustav-Eikaas** [comment]
Affected apps
- [ ] Workorder
- [ ] Loop
- [ ] Punch
- [ ] Handover

**Comment by espenkalle** [comment]
Ikke lø ws 4.0.3 ut enda vel?

**Review by espenkalle — APPROVED** [review]

**Comment by Gustav-Eikaas** [comment]
deploy test

**Comment by AreWiv** [comment]
Tested - verified for 
- Workorder
- Loop
- Punch

Handover does not seem to work as expected.

Would also ask for slightly better description - which popover/box is affected.

**Pull request merged**
