### PR TITLE
feat: :sparkles: add bookmarks to handover

### PR DESCRIPTION
**Pull request by Gustav-Eikaas**
## Status
Seems to work as intended. I made a generic hook to make it easy to maintain and implement for all apps. 
Works in the CLI, but there is a bug with the bookmarks sidesheet. 
Tested by making a useEffect with a setTimeout that sets a bookmark by id after 5seconds

## Next steps:
I want to wait for handover to go into production on JC Castberg & FPP before adding to the rest of the applications

### CODE REVIEW

**Review by espenkalle — APPROVED** [review]

**Comment by Gustav-Eikaas** [comment]
deploy test

**Comment by Gustav-Eikaas** [comment]
deploy test

**Comment by ken-mellem** [comment]
Why is this a Draft? @Gustav-Eikaas

**Comment by Gustav-Eikaas** [comment]
Because it's a WIP

**Comment by Gustav-Eikaas** [comment]
deploy test

**Comment by Gustav-Eikaas** [comment]
deploy test

**Comment by Gustav-Eikaas** [comment]
deploy test

**Pull request merged**
